### ISSUE TITLE
Returns empty string when incorrect url is given

### ISSUE THREAD

**Issue by livespotty** [18F/cf-route-lookup#6]
When wrong url is given it returns empty without any error message or 'url not found' message.

Eg., cf lookup-route something.nothing.com

< returns empty >

**Comment by afeld** [comment]
That's strange...I see

```
$ cf lookup-route something.nothing.com
2017/01/09 15:27:27 Error retrieving apps: Could not find matching domain.
```

Are you using v1.0.0, or the latest `master` on GitHub? Are you on Windows, or Mac/Linux?

**Comment by livespotty** [comment]
I am using the latest master. This is on windows. cf version 6.21.1+6fd3c9f-2016-08-10

**Comment by afeld** [comment]
Hmmmm...wonder if it's a Windows-specific issue. Will try and test soon.

**Comment by kinjelom** [comment]
I think I have fixed it: https://github.com/18F/cf-route-lookup/pull/9/commits/4cadf7ff03a5bd6bf7980745fa9b23b4f00eba53#diff-651a84f8ad6a38c1f7ccdf63f2692410R35
